/* Insert */
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,
                      mobile_number,
                      home_number,
                      email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader) 
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mr', 
                       'Bloodseeker', 
                       '771777', 
                       'UK', 
                       '4123', 
                       '7876565371', 
                       '8767654', 
                       'bloodseeker@gmail.com', 
                       'Magar', 
                       'Student', 
                       'Yes', 
                       'M', 
                       'Cancer', 
                       12345, 
                       'Australian', 
                       12/12/12, 
                       '01/01/2002', 
                       'Computing', 
                       '2016', 
                       'Computer', 
                       null, 
                       null, 
                       null, '1');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mrs', 
                       'Lina', 
                       '771776', 
                       'UK', 
                       '4123', 
                       '7876565373', 
                       '8767653', 
                       'lina@gmail.com', 
                       'Cheetri', 
                       'Student', 
                       'No', 
                       'F', 
                       'Diabities', 
                       12346, 
                       'French', 
                       11/12/12, 
                       '01/01/1997', 
                       'Computing', 
                       '2016', 
                       'Computing', 
                       null, 
                       null, 
                       null, '2');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mrs', 
                       'Luna', 
                       '771775', 
                       'Australia', 
                       '4124', 
                       '7876565374', 
                       '8767652', 
                       'luna@gmail.com', 
                       'Bhahun', 
                       'Teacher', 
                       'Yes', 
                       'F', 
                       'Pressure', 
                       12347, 
                       'Nepali', 
                       10/12/12, 
                       '01/01/1992', 
                       'Health', 
                       '2016', 
                       'Farm', 
                       null, 
                       null, 
                       null, '3');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mrs', 
                       'Mirana', 
                       '771774', 
                       'Australia', 
                       '4124', 
                       '7876565375', 
                       '8767651', 
                       'mirana@gmail.com', 
                       'Newar', 
                       'Farmer', 
                       'Yes', 
                       'F', 
                       'Fracture', 
                       12348, 
                       'American', 
                       9/12/12, 
                       '01/01/1995', 
                       'Health', 
                       '2016', 
                       'Health', 
                       null, 
                       null, 
                       null, '4');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mrs', 
                       'Rylai', 
                       '771772', 
                       'UK', 
                       '4123', 
                       '7876565376', 
                       '8767650', 
                       'ryalia@gmail.com', 
                       'Hindu', 
                       'Manager', 
                       'Yes', 
                       'F', 
                       'Flu', 
                       12349, 
                       'Japanese', 
                       8/12/12, 
                       '01/01/1997', 
                       'Computing', 
                       '2019', 
                       'Computing', 
                       null, 
                       null,
                       null, '5');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mr', 
                       'Wraith', 
                       '771771', 
                       'UK', 
                       '4123', 
                       '7876565377', 
                       '8767655', 
                       'wraith@gmail.com', 
                       'Magar', 
                       'Student', 
                       'No', 
                       'M', 
                       'Gastick', 
                       12340, 
                       'Mongolian', 
                       7/12/12, 
                       '01/01/1998', 
                       'Science', 
                       '2016', 
                       'Farm', 
                       null,
                       null,
                       null, '6');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mr', 
                       'Mage', 
                       '771712', 
                       'UK', 
                       '4123', 
                       '7876565378', 
                       '8767656', 
                       'mage@gmail.com', 
                       'Magar', 
                       'Manager', 
                       'Yes', 
                       'M', 
                       'Malaria', 
                       12344, 
                       'Korean', 
                       6/12/12, 
                       '01/01/1998', 
                       'Farming', 
                       '2011', 
                       'Health', 
                       null,
                       null, 
                       null, '7');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mr', 
                       'Void', 
                       '771781', 
                       'UK', 
                       '4123', 
                       '7876565379', 
                       '8767657', 
                       'void@gmail.com', 
                       'Newar', 
                       'Scientist', 
                       'No', 
                       'M', 
                       'Backache', 
                       12343, 
                       'African', 
                       5/12/12, 
                       '01/01/1995', 
                       'Science', 
                       '2016', 
                       'Programmer', 
                       null,
                       null,
                       null, '8');
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader)
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mr', 
                       'Kunkka', 
                       '77178765', 
                       'UK', 
                       '4123', 
                       '7876565370', 
                       '8767658', 
                       'kunkaa@gmail.com', 
                       'Debeasi', 
                       'Student', 
                       'Yes', 
                       'M', 
                       'Daibitis', 
                       12342, 
                       'Chinese', 
                       4/12/12, 
                       '01/01/2000', 
                       'Computing', 
                       '2012', 
                       'Health', 
                       'Chun li',
                       'chunli@gmail.oom',
                       '9876766545', null);
                       
INSERT INTO volunteer(volunteer_id, title, 
                      name,
                      universityRefNo,
                      address_line_1,
                      postcode,mobile_number,
                      home_number,email,
                      ethnic_group,
                      volunteer_type, 
                      register_disable,
                      gender,
                      medical_details,
                      passport_number,
                      nationality,
                      passport_expiry_date,
                      date_of_birth,
                      course_name,
                      course_year,
                      area_of_work,
                      staff_manager_name,
                      staff_manager_email,
                      staff_manager_phone,
                      team_leader) 
               VALUES (volunteer_id_seq.NEXTVAL, 
                       'Mrs', 
                       'Venegar', 
                       '77172233', 
                       'UK', 
                       '4123', 
                       '7876565372', 
                       '8767659', 
                       'venegar@gmail.com', 
                       'Rhodes', 
                       'Farmer', 
                       'Yes', 
                       'F', 
                       'Flu', 
                       12341, 
                       'Indian', 
                       3/12/12, 
                       '01/01/2001', 
                       'Computing', 
                       '2018', 
                       'Health', 
                       null,
                       null,
                       null, '10');

INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Gardening');

INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Knitting');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Baking');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Cooking');
                                      
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Playing');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Studying');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Programming');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Networking');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Riding');
                   
INSERT INTO skill (skill_id, 
                   skill_name) 
            Values(skill_id_seq.NEXTVAL,
                   'Eating');        
                   
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '1', 1);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '2', 2);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '3', 3);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '4', 4);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '5', 5);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '6', 6);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '7', 7);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '8', 8);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '9', 9);
INSERT INTO vol_skill VALUES(vol_skill_id_seq.NEXTVAL, '10', 10);

INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Kathmandu', 
                                     '72', 
                                     12340, 
                                     12230, 
                                     'Hilly', 
                                     'Nepal', 
                                     null);
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Mustang', 
                                     '71', 
                                     12341, 
                                     12231, 
                                     'Mountain', 
                                     'Nepal', 
                                     null);
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Pune', 
                                     '78', 
                                     12342, 
                                     12232, 
                                     'Mountain', 
                                     'India', 
                                     'Tomato');
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Kulki', 
                                     '75', 
                                     12343, 
                                     12233, 
                                     'Hilly', 
                                     'Nepal', 
                                     null);
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Baglung', 
                                     '76', 
                                     12344, 
                                     12234, 
                                     'Mountain', 
                                     'Nepal', 
                                     'Potato');
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Biratnagar', 
                                     '73', 
                                     12345, 
                                     12235, 
                                     'Terai', 
                                     'Nepal', 
                                     'Tomato');
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Birgung', 
                                     '77', 
                                     12346, 
                                     12236, 
                                     'Tarai', 
                                     'Nepal', 
                                     'Ghee');
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Pokhara', 
                                     '89', 
                                     12347, 
                                     12237, 
                                     'Mountain', 
                                     'Nepal', 
                                     'Raspberry');
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Manang', 
                                     '82', 
                                     12348, 
                                     12238, 
                                     'Mountain', 
                                     'Nepal', 
                                     'Apple');
                                     
INSERT INTO project_location VALUES (project_location_seq.NEXTVAL, 
                                     'Maheshwswori', 
                                     '80', 
                                     12349, 
                                     12239, 
                                     'Tarai', 
                                     'Nepal', 
                                     null);


INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Indonesia Summer 2001', 
                           'conservation', 
                           '01/02/2001', 
                           '01/02/2002', 
                           2000, 
                           'Yes', 
                           'Hard Working',
                           'Yes', 
                           'No', 
                           null, 
                           null, 
                           null,
                           'RedBull', 
                           'No', 
                           'Yes', 
                           '59', 
                           1);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Finland Winter 2001', 
                           'Deforestation awarness', 
                           '01/02/2003', 
                           '01/02/2004', 
                           3000, 
                           'Yes', 
                           'Intelligent',
                           'Yes', 
                           'No', 
                           null, 
                           null, 
                           'VolksWagen', 
                           'Snergy', 
                           'No', 
                           '9', 
                           '58', 
                           2);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Unity Fiesta 2001', 
                           'Game Design', 
                           '01/02/2005', 
                           '01/02/2006', 
                           2003, 
                           'Yes', 
                           'Astute',
                           'Yes', 
                           'No', 
                           'Yes', 
                           'No', 
                           null, 
                           'Wowz', 
                           'No', 
                           'Yes', 
                           '57', 
                           3);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'CryEngine Demo', 
                           'Game Demo', 
                           '01/02/2007', 
                           '01/02/2008', 
                           1234, 
                           'Yes', 
                           'Bright',
                           'No', 
                           'No', 
                           'No', 
                           'Yes', 
                           'Maruti', 
                           'Tata', 
                           'No', 
                           'Yes', 
                           '56', 
                           4);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Switzerland Summer 2001', 
                           'Conservation', 
                           '01/02/2007', 
                           '01/02/2008', 
                           20020, 
                           'Yes', 
                           'Brilliant',
                           'Yes', 
                           'Yes', 
                           'Yes', 
                           'No', 
                           'Hyundai', 
                           'Gment', 
                           'No', 
                           'Yes', 
                           '55', 
                           5);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'France Trance', 
                           'Trance Festival', 
                           '01/02/2001', 
                           '01/04/2002', 
                           2222, 
                           'Yes', 
                           'Creative',
                           'Yes', 
                           'No', 
                           'No', 
                           'No', 
                           'Shake', 
                           'B&R', 
                           'No', 
                           'Yes', 
                           '54', 
                           6);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Summer 1995', 
                           'Awarness', 
                           '01/02/2001', 
                           '01/02/2002', 
                           2000, 
                           'Yes', 
                           'Imaginative',
                           'No', 
                           'Yes', 
                           'Yes', 
                           'No', 
                           'Checker', 
                           null, 
                           null, 
                           null, 
                           '52', 
                           7);
                          
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Lei The Summer Queen 1951', 
                           'Protection Form UV Rays', 
                           '01/02/2005', 
                           '01/10/2002', 
                           8922, 
                           'Yes', 
                           'Inventive',
                           'Yes', 
                           'Yes', 
                           'Yes', 
                           'No', 
                           'Raymonds', 
                           'Shrestha', 
                           'No', 
                           'Yes', 
                           '52', 
                           8);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Malaysia Sinker 2001', 
                           'Sinkination', 
                           '01/02/2001', 
                           '01/12/2001', 
                           9000, 
                           'No', 
                           'Original',
                           'Yes', 
                           'Yes', 
                           'No', 
                           'Yes', 
                           'WittyInc', 
                           'Highbrow', 
                           'No', 
                           null, 
                           '41', 
                           9);
                           
INSERT INTO project VALUES(project_id_seq.NEXTVAL, 
                           'Philiphines Genting 2001', 
                           'Awarness on TSunami', 
                           '01/02/2000', 
                           '01/02/2002', 
                           2222, 
                           'Yes', 
                           'Rational',
                           'Yes', 
                           'No', 
                           'No', 
                           'Yes', 
                           'Sharp', 
                           null,
                           null,
                           null,
                           '21', 
                           10);
                           
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Code', 
                        '01/02/2010', 
                        '01/01/2011', 
                        '6', 
                        1);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Cook', 
                        '01/02/2011', 
                        '01/01/2012', 
                        '5', 
                        2);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Read', 
                        '01/02/2012', 
                        '01/01/2013', 
                        '4', 
                        3);
                       
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Help', 
                        '01/02/2013', 
                        '01/01/2014', 
                        '3', 
                        4);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Go', 
                        '01/02/2014', 
                        '01/01/2015', 
                        '2', 
                        5);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Sit', 
                        '01/02/2015', 
                        '01/01/2016', 
                        '1', 
                        6);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Give', 
                        '01/02/2016', 
                        '01/01/2017', 
                        '14', 
                        7);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Study', 
                        '01/02/2017', 
                        '01/01/2018', 
                        '12', 
                        8);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Aware', 
                        '01/02/2018', 
                        '01/01/2019', 
                        '11', 
                        9);
                        
INSERT INTO task VALUES(task_id_seq.NEXTVAL, 
                        'Stay', 
                        '01/02/2019', 
                        '01/01/2020', 
                        '13', 
                        10);
                        
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              1, 
                              1);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              2, 
                              2);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              3, 
                              3);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              4, 
                              4);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              5, 
                              5);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              6, 
                              6);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              7, 
                              7);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              8, 
                              8);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              9, 
                              9);
                              
INSERT INTO skill_task VALUES(task_skill_id_seq.NEXTVAL, 
                              10, 
                              10);
                              
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Code', 
                                 'Sunday', 
                                 'jan-10-2014', 
                                 1);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Knit', 
                                 'Monday', 
                                 'jan-11-2015', 
                                 2);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Eat', 
                                 'Tuesday', 
                                 'jan-12-2015', 
                                 3);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Sleep', 
                                 'Wednessday', 
                                 'jan-13-2016', 
                                 4);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Drink', 
                                 'Monday', 
                                 'jan-16-2016', 
                                 5);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Sit', 
                                 'Monday', 
                                 'jan-17-2011', 
                                 6);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Stay', 
                                 'Friday', 
                                 'jan-09-2011', 
                                 7);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Read', 
                                 'Saturday', 
                                 'jan-19-2012', 
                                 8);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Study', 
                                 'Sunday', 
                                 'jan-14-2015', 
                                 9);
                                 
INSERT INTO task_activity VALUES(activity_id_seq.NEXTVAL, 
                                 'Learn', 
                                 'Sunday', 
                                 'jan-21-2016', 
                                 10);
                                 
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Bloodseeker',
                           'bloodseeker@gmail.com',
                           '9876545670',
                           'Seeker',
                           1);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Mirana',
                           'mirana@gmail.com',
                           '9876545671',
                           'Leaper',
                           2);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Cammy',
                           'cammy@gmail.com',
                           '9876545672',
                           'Farmer',
                           3);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Rubick',
                           'rubick@gmail.com',
                           '9876545673',
                           'Engineer',
                           4);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Magnus',
                           'magnus@gmail.com',
                           '9876545674',
                           'Scientist',
                           5);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Wraith',
                           'wraith@gmail.com',
                           '9876545605',
                           'Doctor',
                           6);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Mage',
                           'mage@gmail.com',
                           '9876545676',
                           'Wrestler',
                           7);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'John',
                           'john@gmail.com',
                           '9876545677',
                           'Astronomer',
                           8);
                           
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Ryalia',
                           'ryalia@gmail.com',
                           '9876545678',
                           'Manager',
                           9);
                                                      
INSERT INTO project_contact VALUES(project_contact_id_seq.NEXTVAL,
                           'Siddartha',
                           'sid@gmail.com',
                           '9876545679',
                           'Coordinator',
                           10);
                                                                
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Road', 
                                  'Micro Van', 
                                  1);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Air', 
                                  'Buddha', 
                                  2);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Air', 
                                  'Yeti', 
                                  3);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Air', 
                                  'Malaysia Airways', 
                                  4);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Road', 
                                  'Mini Van', 
                                  5);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Road', 
                                  'Bus', 
                                  6);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Air', 
                                  'Express', 
                                  7);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Road', 
                                  'Maruti', 
                                  8);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Road', 
                                  'Jeep', 
                                  9);
                                  
INSERT INTO travel_option VALUES (task_id_seq.NEXTVAL, 
                                  'Air', 
                                  'Dubai Express', 
                                  10);
                                  
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2015, 
                                   '1230', 
                                   'Air', 
                                   11, 
                                   '1');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2016, 
                                   '1231', 
                                   'Air', 
                                   12, 
                                   '2');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2012, 
                                   '1232', 
                                   'Air', 
                                   13, 
                                   '3');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2012, 
                                   '1233', 
                                   'Bus', 
                                   14, 
                                   '4');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2011, 
                                   '1234', 
                                   'Air', 
                                   15, 
                                   '5');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2011, 
                                   '1235', 
                                   'Air', 
                                   16, 
                                   '6');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2013, 
                                   '1236', 
                                   'Train', 
                                   17, 
                                   '7');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2015, 
                                   '1237', 
                                   'Air', 
                                   18, 
                                   '8');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2016, 
                                   '1238', 
                                   'Bus', 
                                   19, 
                                   '9');
                                   
INSERT INTO travel_booking VALUES (booking_id_seq.NEXTVAL, 
                                   2015, 
                                   '1239', 
                                   'Air', 
                                   20, 
                                   '10');

